---
- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /opt/fzf
    depth: 1
    force: yes
  become: yes
  tags: [ fzf ]

- name: set fzf directory permissions
  file:
    path: /opt/fzf
    state: directory
    mode: '777'
    recurse: yes
  become: yes
  tags: [ fzf ]

- name: install fzf
  command: ./install --all
  args: 
    chdir: /opt/fzf
  tags: [ fzf ]

- name: clone Tmux Package Manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    depth: 1
  tags: [ tmux ]

- name: test oh-my-zsh installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  tags: [ zsh ]

- name: download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: u+x
  when: not oh_my_zsh.stat.exists
  tags: [ zsh ]

- name: install oh-my-zsh
  shell: 
  args:
    cmd: ./oh-my-zsh.sh
    chdir: /tmp
  when: not oh_my_zsh.stat.exists
  tags: [ zsh ]

- name: cleanup 
  file:
    path: /tmp/oh-my-zsh.sh
    state: absent
  tags: [ always ]

- name: correct fzf directory permissions
  file:
    path: /opt/fzf
    state: directory
    mode: '755'
    recurse: yes
  become: yes
  tags: [ fzf ]

- name: download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: 'u+x'
  tags: [ rust ]

- name: install rustup
  command: ./rustup-init.sh -y -q
  args: 
    chdir: /tmp
  tags: [ rust ]


