---
- name: github sources
  command: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
  #TODO sudo apt update and gh install not tested on Ubuntu
- name: install packages  
  apt: 
    name: '{{packages}}'
    update_cache: true
    state: present
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install casks
  shell: 
  args:
    cmd: "brew install {{ item }}"
  when: ansible_distribution == 'MacOSX'
  with_items: 
    - "{{ casks }}"

- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /opt/fzf
    depth: 1
    force: yes
  become: yes

- name: set fzf directory permissions
  file:
    path: /opt/fzf
    state: directory
    mode: '777'
    recurse: yes
  become: yes

- name: install fzf
  command: ./install --all
  args: 
    chdir: /opt/fzf

- name: clone Tmux Package Manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    depth: 1

- name: test oh-my-zsh installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh

- name: download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: u+x
  when: not oh_my_zsh.stat.exists

- name: install oh-my-zsh
  shell: 
  args:
    cmd: ./oh-my-zsh.sh
    chdir: /tmp
  when: not oh_my_zsh.stat.exists

- name: cleanup 
  file:
    path: /tmp/oh-my-zsh.sh
    state: absent

- name: test added to bashrc
  shell: grep -c "exec zsh" ~/.bashrc || true 
  register: exec_in_bash

- lineinfile: 
    path: ~/.bashrc
    line:  "if [ -t 1 ]; then\n exec zsh\nfi"
  when: not exec_in_bash.stdout == "1"

- name: brew upgrade
  shell: 
  args:
    cmd: brew upgrade 
  when: ansible_distribution == 'MacOSX'
