---
- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /opt/fzf
    depth: 1
    force: true
  become: true
  tags: [fzf]

- name: set fzf directory permissions
  file:
    path: /opt/fzf
    state: directory
    mode: '777'
    recurse: true
  become: true
  tags: [fzf]

- name: install fzf
  command: ./install --all
  args:
    chdir: /opt/fzf
  tags: [fzf]

- name: clone Tmux Package Manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    depth: 1
  tags: [tmux]

- name: test oh-my-zsh installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  tags: [zsh]

- name: download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: u+x
  when: not oh_my_zsh.stat.exists
  tags: [zsh]

- name: install oh-my-zsh
  shell:
  args:
    cmd: ./oh-my-zsh.sh
    chdir: /tmp
  when: not oh_my_zsh.stat.exists
  tags: [zsh]

- name: cleanup
  file:
    path: /tmp/oh-my-zsh.sh
    state: absent
  tags: [always]

- name: correct fzf directory permissions
  file:
    path: /opt/fzf
    state: directory
    mode: '755'
    recurse: true
  become: true
  tags: [fzf]
  
- name: node version manager
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: rustup
  shell: >
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  args:
    creates: "{{ ansible_env.HOME }}/.rustup"
