---
- name: shell packages  
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - silversearcher-ag
  become: yes

- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /home/{{ ansible_user_id }}/.fzf
  depth: 1

- name: install fzf
  command: ./install --all
  args: 
    chdir: /home/{{ ansible_user_id }}/.fzf

- name: clone tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: /home/{{ ansible_user_id }}/.tmux/plugins/tpm
  depth: 1
