---
- name: create .config
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0777'

- name: link files
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/.{{ item }}
        state=link
        force=true
  with_items: '{{dotfile_files}}'

- name: link zsh dir
  file: src={{ ansible_env.PWD }}/zsh/
        path=~/.zsh
        state=link
        force=true
