export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/node@16/bin:$PATH"


plugins=(git vi-mode)

#
# History
#

export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

#
# Options
#

setopt autocd               # .. is shortcut for cd .. (etc)
setopt autoparamslash       # tab completing directory appends a slash
setopt autopushd            # cd automatically pushes old dir onto dir stack
setopt clobber              # allow clobbering with >, no need to use >!
setopt correct              # command auto-correction
setopt correctall           # argument auto-correction
setopt noflowcontrol        # disable start (C-s) and stop (C-q) characters
setopt nonomatch            # unmatched patterns are left unchanged
setopt histignorealldups    # filter duplicates from history
setopt histignorespace      # don't record commands starting with a space
setopt histverify           # confirm history expansion (!$, !!, !foo)
setopt ignoreeof            # prevent accidental C-d from exiting shell
setopt interactivecomments  # allow comments, even in interactive shells
setopt printexitvalue       # for non-zero exit status
setopt pushdignoredups      # don't push multiple copies of same dir onto stack
setopt pushdsilent          # don't print dir stack after pushing/popping
setopt sharehistory         # share history across shells

#
# Other
#
source $ZSH/oh-my-zsh.sh
source $HOME/.zsh/aliases
source $HOME/.zsh/bindings
source $HOME/.zsh/colors
source $HOME/.zsh/theme
source $HOME/.zsh/functions
source $HOME/.zsh/corrections
source $HOME/.zsh/hooks

# Local and host-specific overrides.

LOCAL_RC=$HOME/.zshrc.local
test -f $LOCAL_RC && source $LOCAL_RC

#
# Third-party
#
# source $HOME/.st1/vendor/docker-cli/contrib/completion/zsh/_docker

# Rustup
. "$HOME/.cargo/env"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source "$HOME/.st1/.vendor/zsh-autosuggestions/zsh-autosuggestions.zsh"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'

# syntax highlighting:
source "$HOME/.st1/.vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

alias luamake=/opt/sumneko/3rd/luamake/luamake

# dotnet
export ASPNETCORE_ENVIRONMENT=Development
