---
- name: zsh | install zsh
  apt: name={{item}}
  become: true 
  with_items:
    - zsh 
    - curl

- name: oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- lineinfile: 
    path: ~/.bashrc
    line:  "if [ -t 1 ]; then\n exec zsh\nfi"
