---
- name: Creates directory
  file: path=~/.nvm state=directory

- name: zsh | install zsh
  apt: name={{item}}
  become: true 
  with_items:
    - zsh 
    - curl
    - ack
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: zsh | install zsh
  pacman: name={{item}}
  become: true 
  with_items:
    - zsh 
    - curl
  when: ansible_distribution == 'Arch Linux' or ansible_distribution == 'Archlinux'

- name: oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- lineinfile: 
    path: ~/.bashrc
    line:  "if [ -t 1 ]; then\n exec zsh\nfi"
