-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     opts = {
--       suggestion = {
--         enabled = true,
--         keymap = {
--           accept = "<C-e>",
--           dismiss = "<C-x>",
--         },
--       },
--     },
--   },
-- }
