---
- name: download
  get_url: 
    url: https://raw.githubusercontent.com/creationix/nvm/v{{nvm_version}}/install.sh
    dest: /tmp/nvm-install.sh
    mode: u+x

- name: install
  shell: 
  args:
    cmd: ./nvm-install.sh
    chdir: /tmp

- name: cleanup 
  file:
    path: /tmp/nvm-install.sh
    state: absent
