---
- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
  depth: 1

- name: clone vim
  git:
    repo: https://github.com/vim/vim.git
    dest: ~/.vimtemp
  depth: 1

- name: install fzf
  command: ./install
  args: 
    chdir: ~/.fzf

- name: vim prerequisites  
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - python-dev
    - python3-dev
    - ruby-dev
    - libperl-dev
    - libncurses5-dev
    - libatk1.0-dev
    - libx11-dev
    - libxpm-dev
    - libxt-dev
    - cmake
  become: yes

- name: vim purge packages 
  apt: 
    name: "{{ item }}"
    state:absent 
    purge:true
  with_items:
    - vim
    - vim-runtime
    - vim-gnome
    - vim-tiny
    - vim-gui-common
  become: yes

- name: vim delete directories
  file: path=/usr/{{ item }} state=absent recurse=no
  become: yes
  with_items:
    - "bin/vim"
    - "local/share/bin"

- name: vim configure 
  command: ./configure --enable-multibyte --enable-perlinterp=dynamic --enable-rubyinterp=dynamic --with-ruby-command=/usr/bin/ruby --enable-pythoninterp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-python3interp --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu --enable-cscope --enable-gui=auto --with-features=huge --with-x --enable-fontset --enable-largefile --disable-netbeans --with-compiledby="st1" --enable-fail-if-missing
  args: 
    chdir: ~/.vimtemp

- name: vim make runtimedir
  command: make VIMRUNTIMEDIR=/usr/local/share/vim/vim81
  args: 
    chdir: ~/.vimtemp

- name: vim make 
  command: make
  args: 
    chdir: ~/.vimtemp
- name: vim make install
  command: make install
  args: 
    chdir: ~/.vimtemp

- name: vim update alternatives editor
  command: update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1
- name: vim update alternatives set editor
  command: update-alternatives --set editor /usr/local/bin/vim

- name: vim update alternatives install vi
  command: update-alternatives --install /usr/bin/vi vi /usr/local/bin/vim 1

- name: vim update alternatives
  command: update-alternatives --set vi /usr/local/bin/vim

- name: install youcompleteme
  command: ./install.py
  args: 
    chdir: ~/.vim/plugged/youcompleteme

- name: vim cleanup 
  file: path=~/{{ item }} state=absent 
  with_items:
    - ".vimtemp"
    - ".fzf"
