---
- name: clone vim
  git:
    repo: https://github.com/vim/vim.git
    dest: /home/{{ ansible_user_id }}/.vimtemp
  depth: 1

- name: vim prerequisites  
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - python-dev
    - python3-dev
    - ruby-dev
    - libperl-dev
    - libncurses5-dev
    - libatk1.0-dev
    - libx11-dev
    - libxpm-dev
    - libxt-dev
    - cmake
  become: yes
  tags: ['never', 'build']

- name: vim purge packages 
  apt: 
    name: "{{ item }}"
    state: absent 
    purge: true
  with_items:
    - vim
    - vim-runtime
    - vim-gnome
    - vim-tiny
    - vim-gui-common
  become: yes
  tags: ['never', 'build']
    
- name: vim delete directories
  file: path=/usr/{{ item }} state=absent recurse=no
  become: yes
  with_items:
    - "bin/vim"
    - "local/share/bin"
  tags: ['never', 'build']

- name: clone vim
  git:
    repo: https://github.com/vim/vim.git
    dest: /home/{{ ansible_user_id }}/.vimtemp
  tags: ['never', 'build']

- name: vim configure 
  command: ./configure --enable-multibyte --enable-perlinterp=dynamic --enable-rubyinterp=dynamic --with-ruby-command=/usr/bin/ruby --enable-pythoninterp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-python3interp --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu --enable-cscope --enable-gui=auto --with-features=huge --with-x --enable-fontset --enable-largefile --disable-netbeans --with-compiledby="st1" --enable-fail-if-missing
  args: 
    chdir: /home/{{ ansible_user_id }}/.vimtemp
  tags: ['never', 'build']

- name: vim make runtimedir
  command: make VIMRUNTIMEDIR=/usr/local/share/vim/vim82
  args: 
    chdir: /home/{{ ansible_user_id }}/.vimtemp
  tags: ['never', 'build']

- name: vim make 
  command: make
  args: 
    chdir: /home/{{ ansible_user_id }}/.vimtemp
  tags: ['never', 'build']

- name: vim make install
  command: make install
  become: yes
  args: 
    chdir: /home/{{ ansible_user_id }}/.vimtemp
  tags: ['never', 'build']

- name: vim update alternatives editor
  command: update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1
  become: yes
  tags: ['never', 'build']

- name: vim update alternatives set editor
  command: update-alternatives --set editor /usr/local/bin/vim
  become: yes
  tags: ['never', 'build']

- name: vim update alternatives install vi
  command: update-alternatives --install /usr/bin/vi vi /usr/local/bin/vim 1
  become: yes
  tags: ['never', 'build']

- name: vim update alternatives
  command: update-alternatives --set vi /usr/local/bin/vim
  become: yes
  tags: ['never', 'build']

- name: build youcompleteme
  command: ./install.py
  tags: ['never', 'build']
  args: 
    chdir: /home/{{ ansible_user_id }}/.vim/bundle/youcompleteme
  tags: ['never', 'build']

- name: vim cleanup 
  file: path=/home/{{ ansible_user_id }}/{{ item }} state=absent 
  with_items:
    - ".vimtemp"
  tags: ['never', 'build']
