---
- name: create config
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0777'
  tags: [neovim]

- name: link neovim config
  file: src=~/.st1/nvim
        path=~/.config/nvim
        state=link
        force=true
  tags: [neovim]

- name: Create config bin directory
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: '0777'
  tags: [neovim]

- name: delete neovim directory
  file:
    path: /opt/neovim
    state: absent
  become: true
  tags: [neovim]

- name: test neovim cloned
  stat:
    path: /opt/neovim
  register: neovim
  become: true
  tags: [neovim]

- name: clone neovim
  git:
    repo: https://github.com/neovim/neovim
    dest: /opt/neovim/
    force: true
    # version: release-0.7
  become: true
  tags: [neovim]

- name: set neovim directory permissions
  file:
    path: /opt/neovim
    state: directory
    mode: '777'
    recurse: true
  become: true
  tags: [neovim]

- name: build neovim
  shell:
  args:
    cmd: make CMAKE_BUILD_TYPE=Release --jobs=4 --silent
    chdir: /opt/neovim
  become: true
  tags: [neovim]

- name: build neovim
  shell:
  args:
    cmd: make install
    chdir: /opt/neovim
  become: true
  tags: [neovim]

- name: clone packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
    force: true
  tags: [neovim, packer]

- name: reset Neovim directory permissions
  file:
    path: /opt/neovim
    state: directory
    mode: '755'
    recurse: true
  become: true
  tags: [neovim]
