---
- name: Create /opt/neovim
  file:
    path: /opt/neovim
    state: directory
    mode: '777'
    recurse: yes
  become: yes

- name: download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /opt/neovim/
    mode: u+x

- name: extract app image
  shell: 
  args:
    cmd: ./nvim.appimage --appimage-extract
    chdir: /opt/neovim
  become: yes

- name: neovim | create symlink
  file: src=/opt/neovim/squashfs-root/usr/bin/nvim
        path=/usr/bin/nvim
        state=link
        force=yes
  become: yes

- name: nvim | cleanup 
  file:
    path: /opt/neovom/nvim.appimage
    state: absent
