---
- name: link neovim config
  file: src={{ ansible_env.PWD }}/nvim/
        path=~/.config/nvim
        state=link
        force=yes

- name: test neovim cloned
  stat:
    path: /tmp/neovim
  register: neovim

- name: clone neovim
  git:
    repo: https://github.com/neovim/neovim
    dest: /tmp/neovim/
    force: yes
  when: not neovim.stat.exists

- name: update neovim latest
  shell: 
  args:
    cmd: git checkout . && git pull
    chdir: /tmp/neovim

- name: build neovim
  shell: 
  args:
    cmd: make CMAKE_BUILD_TYPE=Release --jobs=4 --silent
    chdir: /tmp/neovim

- name: build neovim
  shell: 
  args:
    cmd: make install
    chdir: /tmp/neovim
  become: yes

- name: clone packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
    force: yes
